#!/usr/bin/env bash

git clone https://github.com/jpegleg/crypt-baller
git clone https://github.com/jpegleg/kali-live-flow
git clone https://github.com/jpegleg/deb-bast
git clone https://github.com/jpegleg/ansible-lb-ldap
git clone https://github.com/jpegleg/draconian-one-way
git clone https://github.com/jpegleg/tls-haproxy-config
git clone https://github.com/jpegleg/ssh-key-hunter
git clone https://github.com/jpegleg/zshrc
git clone https://github.com/jpegleg/archive-spider
git clone https://github.com/jpegleg/netstew
git clone https://github.com/jpegleg/plumbus-freezer
git clone https://github.com/jpegleg/bash-jwt
git clone https://github.com/jpegleg/cryptoCore
git clone https://github.com/jpegleg/iterblock
git clone https://github.com/jpegleg/magic-spell
git clone https://github.com/jpegleg/jpegleg-lib
git clone https://github.com/jpegleg/jpegleg-vimrc
git clone https://github.com/jpegleg/net-gargoyle
git clone https://github.com/jpegleg/sec-alarm
git clone https://github.com/jpegleg/character-lib
git clone https://github.com/jpegleg/spiral-arm
git clone https://github.com/jpegleg/h2b2
git clone https://github.com/jpegleg/forcematrix
git clone https://github.com/jpegleg/mailfixer
git clone https://github.com/jpegleg/change-watcher
git clone https://github.com/jpegleg/fe-html-template
git clone https://github.com/jpegleg/flying-m
git clone https://github.com/jpegleg/heaven-pki
git clone https://github.com/jpegleg/recurse-catalog
git clone https://github.com/jpegleg/hist-event-reaction
git clone https://github.com/jpegleg/readhist.pl
git clone https://github.com/jpegleg/pattern-learner
git clone https://github.com/jpegleg/tcp-bunny
git clone https://github.com/jpegleg/pipe2sec
git clone https://github.com/jpegleg/careful-squid
git clone https://github.com/jpegleg/metarc
git clone https://github.com/jpegleg/revsec
git clone https://github.com/jpegleg/sec-enforce
git clone https://github.com/jpegleg/time-sort-tar
git clone https://github.com/jpegleg/expiry-hunter
git clone https://github.com/jpegleg/eaas-deployment-d
git clone https://github.com/jpegleg/eaas-deployment-e
git clone https://github.com/jpegleg/tls-library
git clone https://github.com/jpegleg/dns_upload
git clone https://github.com/jpegleg/open-gslb_template
git clone https://github.com/jpegleg/jpegleg-registry
git clone https://github.com/jpegleg/firewalld-autoban
git clone https://github.com/jpegleg/freebsd-arpsec
git clone https://github.com/jpegleg/badger-chainz
git clone https://github.com/jpegleg/nginx-le-deploy
git clone https://github.com/jpegleg/1-vm-enterprise
git clone https://github.com/jpegleg/ansible-reports
git clone https://github.com/jpegleg/c7_jenkins_agent
git clone https://github.com/jpegleg/d10_jenkins_agent
git clone https://github.com/jpegleg/snake_bounce
git clone https://github.com/jpegleg/wazuh-console-tools
git clone https://github.com/jpegleg/net-gargoyle2
git clone https://github.com/jpegleg/gluster_cluster
git clone https://github.com/jpegleg/redis_compile
