#!/usr/bin/env bash

for repo in $(grep jpegleg rm-and-clone.sh | grep -o https.*); do
  echo $repo
  target=$(echo "$repo" | rev | cut -d'/' -f1 | rev)
  recurse-catalog /srv/ https://github.com/jpegleg/ "$target" jpegleg-git
done
